language: php

sudo: false

php:
# v5.3 is disabled because Codeception v2.x does not support it. Using v1.8 has an issue with log directory permissions.
# - 5.3

# v5.4 is disabled because Codeception v2.1.x does not support it. Causing the following error.
# PHP Fatal error:  Call to undefined function GuzzleHttp\Handler\curl_reset() in CurlFactory.php on line 78
# See https://github.com/Codeception/Codeception/issues/2124
# - 5.4

- 5.5
- 5.6
- 7.0
- 7.1
- 7.2

# HHVM is disabled because wp-cli causes an error.
# - hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0 TEMP=/tmp

matrix:
    include:
        - php: 5.5
          env: WP_VERSION=latest WP_MULTISITE=1 TEMP=/tmp

install:
    - bash test/install.sh -c test/settings.travis.cfg 

before_script:
    - php -S 127.0.0.1:4000 &
    - sleep 3
  
script: |
    if [[ $TRAVIS_PHP_VERSION = '5.6' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then 
        bash test/run.sh -c test/settings.travis.cfg -l 'coverage.xml'; 
    else 
        bash test/run.sh -c test/settings.travis.cfg; 
    fi

after_script: |
    if [[ $TRAVIS_PHP_VERSION = '5.6' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then 
        wget https://scrutinizer-ci.com/ocular.phar --no-check-certificate; 
        php ocular.phar code-coverage:upload --format=php-clover 'coverage.xml';
        php test/coverage-checker.php 'coverage.xml' 80;
    fi
